project:
  type: website
  output-dir: _site
  render:
    - index.qmd
  resources:
    - dataset/energy-plan-pubcom-sample/pair_relation_viewer.html
    - dataset/energy-plan-pubcom-sample/entity_opinions.json
    - dataset/energy-plan-pubcom-sample/pair_relations.json

website:
  title: "広聴AI keyword-curation ワークフロー"
  navbar: false
  search: false

format:
  html:
    toc: true
    theme: cosmo
    search: false
